# Calculations with NumPy Arrays

One of the most powerful features of NumPy is the operations you can perform on its arrays. In this notebook we will cover the topics of:

- Mathematical operations
- Statistical operations
- Sorting and advanced indexing

## Basic Mathematical Operations

NumPy allows us to use mathematical operators such as `+` and `*` to perform *element-wise* operations. This means that these operations are applied element by element.

In [1]:
import numpy as np

a = np.array([20,30,40,50])
b = np.arange(1, 5)
print(a)
print(b)

[20 30 40 50]
[1 2 3 4]


In [2]:
print('Subtraction:\t', a - b)
print('Addition:\t', a + b)
print('Multiplication:\t', a * b)
print('Division:\t', a / b)
print('Exponentiation:\t', a ** b)

Subtraction:	 [19 28 37 46]
Addition:	 [21 32 43 54]
Multiplication:	 [ 20  60 120 200]
Division:	 [20.         15.         13.33333333 12.5       ]
Exponentiation:	 [     20     900   64000 6250000]


Note that to perform these operations, the arrays must have compatible sizes. In simple cases this means that arrays must have the same shapes.

In [3]:
a1 = np.r_[a, 60, 70]
print(a1)
print(b)
try:
    print(a1 + b)
except ValueError as e:
    print('Error:', e)

[20 30 40 50 60 70]
[1 2 3 4]
Error: operands could not be broadcast together with shapes (6,) (4,) 


NumPy deals with differences in shape using its *broadcasting rules*, which is where this error message is coming from. The error is telling us that NumPy tried to perform the operation after applying the broadcasting rules but still couldn't do it, so basically the shapes of these arrays were incompatiable for addition.

For a quick summary of the broadcasting rules see [here](https://numpy.org/doc/stable/user/quickstart.html#broadcasting-rules). We'll return to this topic later to learn more about it.

NumPy also allows you to perform the same operation to each element, for example to multiply each element in an array by 2, or to add 15 onto each element.

In [15]:
print(b)
print(b * 2)
print(b + 15)

[1 2 3 4]
[2 4 6 8]
[16 17 18 19]


We can also check conditions against each element in an array, for example to check if each element is less than 40.

In [5]:
print(a)
print(a < 40)
print(b)
print(b < 40)

[ 20  60 120 200]
[ True False False False]
[1 2 3 4]
[ True  True  True  True]


We can update arrays in-place with arithmetic operations similar to how we do it in Python: we place the arithmetic operation symbol to the left of the equals sign, e.g. `+=`.

In [13]:
a1 = a.copy()
print(a1)
a1 += 3
print(a1)

[ 20  60 120 200]
[ 23  63 123 203]


In [14]:
# The above is the same as
print(a)
a = a + 3
print(a)

[ 20  60 120 200]
[ 23  63 123 203]


In [4]:
# We can also put arrays on the right hand side
print(a)
print(b)
a *= b
print(a)

[20 30 40 50]
[1 2 3 4]
[ 20  60 120 200]


**Challenge:** Create two arrays with shapes (2, 3), update the first one so its values are multiplied by 2, then update the second one by adding the first to it.

Look carefully at the resulting numbers and make sure you understand how each is computed.

In [ ]:
arr1 = np.arange(1,7).reshape((2,3))
print(arr1)
arr2 = np.arange(7,13).reshape((2,3))
print(arr2)
arr1 *= 2
print(arr1)
arr2 += arr1
print(arr2)

# a1 = np.array([2, 4, 6, 8, 10, 12]).reshape((2, 3))
# a2 = np.array([20, 25, 30, 35, 40, 45]).reshape((2, 3))
# a1 *= 2
# a2 += a1
# print(a1)
# print(a2)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]
[[ 2  4  6]
 [ 8 10 12]]
[[ 9 12 15]
 [18 21 24]]


## Statistical Operations

NumPy supports many unary operations to compute statistics about our arrays, such as minimums, maximums, and averages.

We can sum values in our arrays. We can either sum all elements, or sum along a particular axis.

In [43]:
b = np.arange(12).reshape(3,4)
print(b)
# Sum all the elements, effectively 0+1+2+...+9+10+11
print(b.sum())

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
66


In [ ]:
# Sum along axis 0, meaning add each row together
print(b.sum(axis=0))
# sum_of_b_0 = b.sum(axis=0)
# print(sum_of_b_0)
# The above is effectively the same as doing this
t = b[0].copy() # copy of the b[0:1, :]
sum_t = t.sum() # sum of the [0123]
print(t)
print(sum_t) 
# print(b)

# Challenge question: why do we have to use copy?
# for row in b[1:]:
#     print(row)
#     t += row
# print(t)

[12 15 18 21]
[0 1 2 3]
6
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [45]:
# Sum along axis 1, meaning add each column together
print(b.sum(axis=1))

[ 6 22 38]


This pattern of having an `axis` parameter is used frequently for methods in NumPy, here's a few more examples.

In [49]:
print(b)
print(b.min())
print(b.max())
print(b.min(axis=1)) # Gives the min across all rows
print(b.max(axis=0)) # Gives the max across all columns
# The cumulative sum across the columns
print(b.cumsum(axis=1))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
0
11
[0 4 8]
[ 8  9 10 11]
[[ 0  1  3  6]
 [ 4  9 15 22]
 [ 8 17 27 38]]


NumPy also provides useful mathematical functions such as sin, cos, and square root. These apply the operations on every element.

In [50]:
print(np.sin(b))
print(np.cos(b))
print(np.sqrt(b))

[[ 0.          0.84147098  0.90929743  0.14112001]
 [-0.7568025  -0.95892427 -0.2794155   0.6569866 ]
 [ 0.98935825  0.41211849 -0.54402111 -0.99999021]]
[[ 1.          0.54030231 -0.41614684 -0.9899925 ]
 [-0.65364362  0.28366219  0.96017029  0.75390225]
 [-0.14550003 -0.91113026 -0.83907153  0.0044257 ]]
[[0.         1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974 2.64575131]
 [2.82842712 3.         3.16227766 3.31662479]]


## Advanced Topics

### Applying Functions

If you have a more complex operation to perform on an array, you might want to use `apply_along_axis`. This applies a function to the one-dimensional slices along a given axis.

For example say we wanted to compute the average of the first and last elements of each row or column in an array.

In [65]:
def my_func(a):
    """Average first and last element of a 1-D array"""
    # print(a[0:3])
    print(a)

    return (a[0] + a[-1]) * 0.5

b = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

print(np.apply_along_axis(my_func, 0, b)) # Averages along the columns
# print(np.apply_along_axis(my_func, 1, b)) # Averages along  teh rows

[1 4 7]
[2 5 8]
[3 6 9]
[4. 5. 6.]


Look at how the slices are passed in to our function by NumPy, it may be counter intuitive at first. You can think of it as NumPy taking a knife and slicing the array in the direction of the axis you specified, then passing those slices to our function.

So if we say `axis=0`, NumPy slices *down* because the rows are stacked *vertically*.

If we say `axis=1`, NumPy slices *right* because the columns are stacked *horizontally*.

**Challenge:** Write code to multiply all the values in each row and replace each row with the result.

In [71]:
def prod(a):
    # r = a[0]
    r = 1
    for value in a:
        r *= value
    return r
# print(np.apply_along_axis(prod, 1, b))

# ...or equivalently
# print(np.apply_along_axis(np.prod, 1, b))

# ...or
print(np.prod(b, axis=1))

[  6 120 504]


### Sorting

As another example, say you wanted to sort the values in each row.

**Challenge:** Before we write the code, which axis do we need to specify to get the values in each row?


In [73]:
b = np.array([[8,1,7], [4,3,9], [5,2,6]])
print(b)
print(np.apply_along_axis(sorted, 1, b))

[[8 1 7]
 [4 3 9]
 [5 2 6]]
[[1 7 8]
 [3 4 9]
 [2 5 6]]


Another way to perform this sorting is to use the `sort` function of NumPy. This also allows us to specify axes to sort.

In [78]:
print(b)
print(np.sort(b)) # Sorts along the last axis, so the columns in this case
print(np.sort(b, axis=0)) # Sorts along the rows
# print(np.sort(b, axis=1)) # Sorts along the columns
print(np.sort(b, axis=None))

[[8 1 7]
 [4 3 9]
 [5 2 6]]
[[1 7 8]
 [3 4 9]
 [2 5 6]]
[[4 1 6]
 [5 2 7]
 [8 3 9]]
[1 2 3 4 5 6 7 8 9]


The above function, `np.sort`, returns a sorted copy of the array. If you want to sort the array in place you can use the `sort` method on the array itself.

In [262]:
b1 = b.copy()
np.sort(b1)
print(b1) # Not sorted
b1.sort()
print(b1) # Sorted

### Advanced Indexing

We can use boolean operators to perform a comparison on each element in an array. These boolean operations generate arrays of booleans.

In [90]:
a = np.arange(12).reshape(3,4)
b = a > 4
# b is an array of booleans with a's shape
print(b)
# Indexing into a with b gives all the values in a greater than 4
print(a[b])

[[False False False False]
 [False  True  True  True]
 [ True  True  True  True]]
[ 5  6  7  8  9 10 11]


This can be very useful in assignments. For example if we wanted set all values in `a` greater than 4 to 0, we could do

In [91]:
a[a < 4] = 0
print(a)

[[ 0  0  0  0]
 [ 4  5  6  7]
 [ 8  9 10 11]]


Indexing with an array can also be performed with actual indices instead of booleans. The best way to understand is with examples.

In [92]:
a = np.arange(12)**2 # the first 12 square numbers
print(a)
i = np.array([1, 1, 3, 8, 5]) # an array of indices
print(a[i]) # the elements of a at the positions i

[  0   1   4   9  16  25  36  49  64  81 100 121]
[ 1  1  9 64 25]


In [93]:
j = np.array([[3, 4],
              [9, 7]]) # a 2D array of indices
print(a[j])

[[ 9 16]
 [81 49]]


Each number in the indexing array specifies the index of the number we want from `a`, then NumPy gives us back an array with the same shape as the indexing array with the values filled in.

If the indexed array `a` is multidimensional, each array of indices refers to the first dimension `a`.

In [94]:
a = np.arange(12).reshape(3, 4)
print(a)

i = np.array([0, 1]) # We want the first and second rows of a
print(a[i])

i = np.array([[0, 1], # We want the first and second rows in one array
              [1, 2]]) # As well as the second and third rows in another array
print(a[i])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[0 1 2 3]
 [4 5 6 7]]
[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 4  5  6  7]
  [ 8  9 10 11]]]


We can also index into both the rows and columns at the same time. In this case the two indexing arrays must have the same shape so NumPy can pick pairs of indexes.

In [95]:
a = np.arange(12).reshape(3,4)
print(a)

i = np.array([[0, 1], # indices for the first dimension of a
              [1, 2]])
j = np.array([[2, 1], # indices for the second dimension
              [3, 3]])

# With the above indices, we are saying we want a 2x2 array with a[0,2] in the top left,
# a[1,1] in the top right, a[1,3] in the bottom left, and a[2,3] in the bottom right
print(a[i, j])

# With this we are using the same rows but we're only grabbing from the third column
# print(a[i, 2])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 2  5]
 [ 7 11]]


In [97]:
a = np.array([4, 3, 2, 1])
print(a)

[4 3 2 1]


**Challenge**: Using `a` from directly above, manually rearrange the numbers in sorted order using an index array. 
The resulting array should look like


```
[1 2 3 4]
```

**Bonus challenge:** Reshape `a` to be of shape (2, 2), then rearrange in sorted order using an index array. The resulting array should look like


```
[[1 2]
 [3 4]]
```


In [104]:
i = np.array([3, 2, 1, 0])
# print(a[i])
# j = np.array([[3,2], [1,0]])
# print(a[j])
# Bonus
a2 = a.reshape((2, 2))
print(a2)
i = np.array([[1, 1], [0, 0]])
j = np.array([[1, 0], [1, 0]])
print(a2[i,j])

[[4 3]
 [2 1]]
[[1 2]
 [3 4]]


### Broadcasting Rules

The broadcasting rules of NumPy define how NumPy treats arrays of different shapes during operations. These are important to understand because there will often be times when we have arrays of different shapes, and if you understand the rules of broadcasting you can save yourself a lot of time and likely make your program more performant.

The idea with broadcasting is to transform the smaller array in the operation into a compatible shape. For example, if we had a 2D array and a 1D array normally we couldn't perform element-wise addition because the 1D array doesn't have matching positions.

From the NumPy documentation:

> The first rule of broadcsting is that if all input arrays do not have the same number of dimensions, a "1" will be repeatedly prepended to the shapes of the smaller arrays until all the arrays have the same number of dimensions.

What this means is that NumPy will transform the smaller array in an operation so that it has the **same number of dimensions** as the larger array.

For example, say we had a 2D array and a 1D array that we wanted to add together:

In [131]:
a2 = np.array([[1,2],
               [3,4]])
a1 = np.array([5, 6])
print(a2)
print(a1)

[[1 2]
 [3 4]]
[5 6]


We can't perform element-wise addition on these yet because they don't have the same number of elements and the elements are not in matching positions.

The first rule comes in here to help get the elements in matching positions: 

`a2` has a shape of (2, 2), and `a1` has a shape of (2,), so when we try to perform an operation on these the first rule of broadcasting transforms `a1` to have a shape of (1, 2).

In [132]:
# broadcast_a1 = a1[np.newaxis, :]
# print(broadcast_a1)

Now we are closer to being able to perform the addition because we have the same number of dimensions. We still can't though because `a1` doesn't have the same number of elements, and this is where the second rule comes in:

> The second rule of broadcasting ensures that arrays with a size of 1 along a particular dimension act as if they had the size of the array with the largest shape along that dimension. The value of the array element is assumed to be the same along that dimension for the “broadcast” array.

What this means is that if a dimension has a size of 1 in an array, it will take the size of the corresponding dimension in the other array by copying itself repeatedly.

In our example, `a1` has a shape of (1,2) while `a2` has a shape of (2,2), so it's first dimension will become 2 to match `a2`'s first dimension. What this looks like is:

In [133]:
# We copy the value in a1's first dimension along a1's first dimension until it
# has the same size as a2's first dimension
# broadcast_a1 = [broadcast_a1[0] for _ in range(a2.shape[0])]
# print(a2.shape[0]) = 2
#
# print(np.array(broadcast_a1))

Now we are done broadcasting and the arrays are compatible! Each element in `a2` now has a corresponding element in `a1` which can be added to it. Putting it all together:

In [134]:
# print(a2)
# print(a1)

# broadcast_a1 = a1[np.newaxis, :]
# broadcast_a1 = np.array([broadcast_a1[0] for _ in range(a2.shape[0])])

# print(a2)
# print(broadcast_a1)

# print(a2 + broadcast_a1)

But NumPy performs these operations automatically for us, so we can just do:

In [135]:
print(a2)
print(a1)
print(a2 + a1)

[[1 2]
 [3 4]]
[5 6]
[[ 6  8]
 [ 8 10]]


NumPy will apply the first rule on the smaller of two arrays, and it will apply the second rule only if all dimensions are compatible after the first rule is applied. You may have figured this out by now, but two dimensions are compatible when

1. they are equal, or
2. one of them is 1.

This is important to understand because it tells you which shapes of arrays can and cannot be broadcast together.

For example consider two 1D arrays, one with length 3 and the other with length 4. They have the same number of dimensions so the first rule doesn't do anything. But the first dimensions of these are not compatible because they are not equal and neither of them is 1.

As another example, consider a 2D array with shape (2,1) and a 3D array of shape (8,4,3). The first rule transforms the 2D array to have shape (1,2,1). Now dimensions 1 and 3 of these two arrays are compatible because the first array has size 1 along those dimensions. However, dimension 2 is incompatible because 4 and 2 are not equal and neither 4 nor 2 is 1.

Let's go through a few more examples:

In [136]:
x = np.arange(4)
xx = x.reshape(4,1)
y = np.ones(5)
z = np.ones((3,4))
print(x)
print(xx)
print(y)
print(z)

[0 1 2 3]
[[0]
 [1]
 [2]
 [3]]
[1. 1. 1. 1. 1.]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [137]:
print(x.shape)
print(y.shape)
try:
    print(x + y)
except ValueError as e:
    print(e)

(4,)
(5,)
operands could not be broadcast together with shapes (4,) (5,) 


In [138]:
print(xx.shape)
print(y.shape)
print((xx + y).shape)
print(xx + y)

(4, 1)
(5,)
(4, 5)
[[1. 1. 1. 1. 1.]
 [2. 2. 2. 2. 2.]
 [3. 3. 3. 3. 3.]
 [4. 4. 4. 4. 4.]]


In [279]:
print(x.shape)
print(z.shape)
print((x + z).shape)
print(x + z)

**Challenge:** Create an array of shape (4, 3), then create an array that **can't** be broadcast with it and create one that **can**.

**Bonus challenge:** Before you print out the result of the compatible arrays, write out what you think the shape of the resulting array will be.

In [ ]:
a4x3 = np.ones((4, 3))
a4x7x3 = np.ones((4, 7, 3))
a7x4x1x3 = np.ones((7, 4, 1, 3))

try:
    a4x3 + a4x7x3
except ValueError as e:
    print(e)

# 1 x 1 x 4 x 3 *
# 7 x 4 x 1 x 3 =>
# 7 x 4 x 4 x 3
r = a4x3 * a7x4x1x3
print(r.shape)
print(r)

## References

- [NumPy Quickstart](https://numpy.org/doc/stable/user/quickstart.html)
- [NumPy Broadcasting](https://numpy.org/doc/stable/user/basics.broadcasting.html)